name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build_and_push_latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker-compose latest
      run: docker-compose build
    - name: Push latest image
      run: docker-compose build
    - name: Build docker-compose tag
      run: GROCY_IMAGE_TAG="$(git describe --abbrev=0 --tags)" docker-compose build
    - name: Push tag
      run: GROCY_IMAGE_TAG="$(git describe --abbrev=0 --tags)" docker-compose push
