name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build_and_push_latest:

    runs-on: ubuntu-latest
    env:
      GROCY_IMAGE_TAG: ${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker-compose build
    - run: docker-compose push
